### ISSUE TITLE
Waiter Support

### ISSUE THREAD

**Issue by danielgtaylor** [danielgtaylor/openapi-cli-generator#18]
Add an OpenAPI extension to provide waiter support that blocks until a specific state has been met. Typically you would do a request on a cadence to return some state information and use a query to match a state in the response to exit the loop.

For example, the configuration for such a feature might look something like:

```yaml
x-cli-waiters:
  order-ready:
    delay: 10
    attempts: 30
    operation: GetOrder
    matchers:
      - select: response.body#order.status
        expected: Ready
```

Assuming the `GetOrder` operation has a required `order-id` parameter, this results in a command something like:

```sh
$ my-cli wait order-ready $ORDER_ID
```

This could also be automatically combined with creation or update operations by mapping response information to parameters on the waiter operation:

```yaml
x-cli-waiters:
  order-ready:
    # ...
    operation: GetOrder
    after:
      PostOrder:
        order-id: response.body#order.id
```

Then you could do something like:

```sh
# With automatic waiter:
$ my-cli post-order <details.json --wait-order-ready

# Without:
$ ID=my-cli post-order <details.json -q order.id
$ my-cli wait order-ready $ID
```

This gets even more difficult with multiple params where you have to save the response and somehow get each param to pass into the `wait` command.
